### ISSUE TITLE
Class 'Data' does not have any method

### ISSUE THREAD

**Issue by Sakvojage** [toitware/artemis-releases#60]
![image](https://github.com/toitware/artemis-releases/assets/7562987/683ca566-52f7-4cfe-964e-33b208906c18)
![image](https://github.com/toitware/artemis-releases/assets/7562987/810dacae-0367-452d-b5c7-674dad44316c)

This happened after upgrade of JAG, Artemis and SDK.
Working on latest Ubuntu if that makes a difference.

**Comment by floitsch** [comment]
We changed the `manufacturer-data` type from `ByteArray` to `io.Data`. This is a safe change, when sending, but I forgot that the same class is also used when receiving.

I will change it back (even though that's also a breaking change).

In the meantime you have two options:
1. convert the `manufacturer_data` back to a ByteArray: `bytes := ByteArray.from device.data.manufacturer_data`, and then use that for the size, lookup.
2. use `byte-size` instead of `size` and `byte-at` instead of `[0]` ...

**Comment by Sakvojage** [comment]
ookay, I see. Thanks for response in 5 minutes:)

**Comment by floitsch** [comment]
Will be fixed in the next Toit release.
